
version: '3.7'
services:
    database:
        container_name: pg_container
        image: postgres:latest
        restart: always
        env_file:
          - database.env
        ports:
          - '5432:5432'
        volumes:
          - ../postgres_data:/var/lib/postgresql/data # <PATH TO STORE POSTGRES DATA>:/var/lib/postgresql/data

